USE [master]
GO

/****** Object:  Database [SiteNoticias]    Script Date: 08/04/2017 09:52:15 ******/
CREATE DATABASE [SiteNoticias]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SiteNoticias', FILENAME = N'C:\site\SiteNoticias.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SiteNoticias_log', FILENAME = N'C:\site\SiteNoticias_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SiteNoticias] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SiteNoticias].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SiteNoticias] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SiteNoticias] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SiteNoticias] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SiteNoticias] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SiteNoticias] SET ARITHABORT OFF 
GO

ALTER DATABASE [SiteNoticias] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SiteNoticias] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [SiteNoticias] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SiteNoticias] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SiteNoticias] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SiteNoticias] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SiteNoticias] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SiteNoticias] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SiteNoticias] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SiteNoticias] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SiteNoticias] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SiteNoticias] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SiteNoticias] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SiteNoticias] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SiteNoticias] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SiteNoticias] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SiteNoticias] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SiteNoticias] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SiteNoticias] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SiteNoticias] SET  MULTI_USER 
GO

ALTER DATABASE [SiteNoticias] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SiteNoticias] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SiteNoticias] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SiteNoticias] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SiteNoticias] SET  READ_WRITE 
GO

